-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [minroot_core]: external functions.
-- The four `core` operations below were emitted by Aeneas as external holes.
-- They are filled here with FAITHFUL, COMPUTABLE models (not axioms) so the
-- `reduce_wide` chain can be reasoned about.  Each keeps the exact `@[rust_fun]`
-- name pattern and type signature Aeneas generated, so the extraction binding is
-- unchanged.  Recall the doubly-wrapped result: the OUTER `Result` is Aeneas'
-- can-fail/diverge monad (`ok`/`do`), the INNER `core.result.Result T E` is
-- Rust's `Result` data type (`.Ok`/`.Err`).
import Aeneas
import MinrootCore.Code.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000
open minroot_core

/-- [core::convert::num::{core::convert::TryFrom<u128, core::num::error::TryFromIntError> for u64}::try_from]:
    Source: '/rustc/library/core/src/convert/num.rs', lines 294:12-294:64
    Name pattern: [core::convert::num::{core::convert::TryFrom<u64, u128, core::num::error::TryFromIntError>}::try_from]
    Visibility: public

    Faithful model of the checked `u64::try_from(x: u128)`: succeeds with the
    low 64 bits exactly when `x` fits in a `u64` (`x.val ≤ U64.max`), otherwise
    returns the conversion error.  `UScalar.cast .U64` is the zero-extend/truncate
    narrowing; on the success branch no truncation occurs so the value is exact. -/
@[rust_fun
  "core::convert::num::{core::convert::TryFrom<u64, u128, core::num::error::TryFromIntError>}::try_from"]
def U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from
  (x : Std.U128) :
  Result (core.result.Result Std.U64
    core.num.error.TryFromIntError)
  :=
  if x.val ≤ Std.U64.max then
    ok (core.result.Result.Ok (Std.UScalar.cast .U64 x))
  else
    ok (core.result.Result.Err core.num.error.TryFromIntError.mk)

/-- [core::result::{core::result::Result<T, E>}::map_err]:
    Source: '/rustc/library/core/src/result.rs', lines 962:4-964:53
    Name pattern: [core::result::{core::result::Result<@T, @E>}::map_err]
    Visibility: public

    Maps the error component through the supplied `FnOnce` closure, threading the
    closure environment `o : O` as the `Self` argument and the error `e : E` as
    the argument (the Aeneas FnOnce calling convention). -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::map_err"]
def core.result.Result.map_err
  {T : Type} {E : Type} {F : Type} {O : Type} (opsfunctionFnOnceOTupleEFInst :
  core.ops.function.FnOnce O E F) :
  core.result.Result T E → O → Result (core.result.Result T F)
  := fun r o =>
  match r with
  | core.result.Result.Ok t => ok (core.result.Result.Ok t)
  | core.result.Result.Err e => do
    let f ← opsfunctionFnOnceOTupleEFInst.call_once o e
    ok (core.result.Result.Err f)

/-- [core::result::{core::ops::try_trait::Try<T, core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, E>}::branch]:
    Source: '/rustc/library/core/src/result.rs', lines 2172:4-2172:64
    Name pattern: [core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch]
    Visibility: public

    The `?`-operator `Try::branch` for `Result`: `Ok t` continues with `t`;
    `Err e` breaks with the residual `Result<Infallible, E>` built as `Err e`. -/
@[rust_fun
  "core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch"]
def core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
  {T : Type} {E : Type} :
  core.result.Result T E → Result (core.ops.control_flow.ControlFlow
    (core.result.Result core.convert.Infallible E) T)
  := fun r =>
  match r with
  | core.result.Result.Ok t =>
    ok (core.ops.control_flow.ControlFlow.Continue t)
  | core.result.Result.Err e =>
    ok (core.ops.control_flow.ControlFlow.Break (core.result.Result.Err e))

/-- [core::result::{core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, F>}::from_residual]:
    Source: '/rustc/library/core/src/result.rs', lines 2187:4-2187:70
    Name pattern: [core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual]
    Visibility: public

    The `?`-operator residual conversion for `Result`.  The residual is a
    `Result<Infallible, E>`, hence necessarily `Err e` (the `Ok` arm carries the
    uninhabited `Infallible` and is discharged by `nomatch`).  The error is
    re-wrapped through the supplied `From F E` conversion. -/
@[rust_fun
  "core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual"]
def
  core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
  (T : Type) {E : Type} {F : Type} (convertFromInst : core.convert.From F E) :
  core.result.Result core.convert.Infallible E → Result (core.result.Result T
    F)
  := fun residual =>
  match residual with
  | core.result.Result.Ok inf => nomatch inf
  | core.result.Result.Err e => do
    let f ← convertFromInst.from_ e
    ok (core.result.Result.Err f)
