-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [minroot_core]: function definitions
import Aeneas
import MinrootCore.Code.Types
import MinrootCore.Code.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

set_option maxRecDepth 4000

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace minroot_core

/-- [minroot_core::field::LIMBS]
    Source: 'crates/minroot-core/src/field.rs', lines 15:0-15:23 -/
@[global_simps, irreducible] def field.LIMBS : Std.Usize := 4#usize

/-- [minroot_core::field::add_limbs::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::add_limbs::closure#3}::call_once]:
    Source: 'crates/minroot-core/src/field.rs', lines 286:46-286:67 -/
def
  field.add_limbs.closure_3.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
  (c : field.add_limbs.closure_3)
  (tupled_args : core.num.error.TryFromIntError) :
  Result error.Error
  := do
  ok error.Error.Truncation

/-- Trait implementation: [minroot_core::field::add_limbs::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::add_limbs::closure#3}]
    Source: 'crates/minroot-core/src/field.rs', lines 286:46-286:67 -/
@[reducible]
def
  field.add_limbs.closure_3.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
  : core.ops.function.FnOnce field.add_limbs.closure_3
  core.num.error.TryFromIntError error.Error := {
  call_once :=
    field.add_limbs.closure_3.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
}

/-- [minroot_core::field::add_limbs::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::add_limbs::closure#2}::call_once]:
    Source: 'crates/minroot-core/src/field.rs', lines 285:46-285:67 -/
def
  field.add_limbs.closure_2.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
  (c : field.add_limbs.closure_2)
  (tupled_args : core.num.error.TryFromIntError) :
  Result error.Error
  := do
  ok error.Error.Truncation

/-- Trait implementation: [minroot_core::field::add_limbs::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::add_limbs::closure#2}]
    Source: 'crates/minroot-core/src/field.rs', lines 285:46-285:67 -/
@[reducible]
def
  field.add_limbs.closure_2.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
  : core.ops.function.FnOnce field.add_limbs.closure_2
  core.num.error.TryFromIntError error.Error := {
  call_once :=
    field.add_limbs.closure_2.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
}

/-- [minroot_core::field::add_limbs::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::add_limbs::closure#1}::call_once]:
    Source: 'crates/minroot-core/src/field.rs', lines 284:46-284:67 -/
def
  field.add_limbs.closure_1.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
  (c : field.add_limbs.closure_1)
  (tupled_args : core.num.error.TryFromIntError) :
  Result error.Error
  := do
  ok error.Error.Truncation

/-- Trait implementation: [minroot_core::field::add_limbs::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::add_limbs::closure#1}]
    Source: 'crates/minroot-core/src/field.rs', lines 284:46-284:67 -/
@[reducible]
def
  field.add_limbs.closure_1.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
  : core.ops.function.FnOnce field.add_limbs.closure_1
  core.num.error.TryFromIntError error.Error := {
  call_once :=
    field.add_limbs.closure_1.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
}

/-- [minroot_core::field::add_limbs::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::add_limbs::closure}::call_once]:
    Source: 'crates/minroot-core/src/field.rs', lines 283:46-283:67 -/
def
  field.add_limbs.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
  (c : field.add_limbs.closure) (tupled_args : core.num.error.TryFromIntError)
  :
  Result error.Error
  := do
  ok error.Error.Truncation

/-- Trait implementation: [minroot_core::field::add_limbs::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::add_limbs::closure}]
    Source: 'crates/minroot-core/src/field.rs', lines 283:46-283:67 -/
@[reducible]
def
  field.add_limbs.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
  : core.ops.function.FnOnce field.add_limbs.closure
  core.num.error.TryFromIntError error.Error := {
  call_once :=
    field.add_limbs.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
}

/-- [minroot_core::field::add_limbs]:
    Source: 'crates/minroot-core/src/field.rs', lines 277:0-288:1 -/
def field.add_limbs
  (a : Array Std.U64 4#usize) (b : Array Std.U64 4#usize) :
  Result (core.result.Result ((Array Std.U64 4#usize) × Bool) error.Error)
  := do
  let i ← Array.index_usize a 0#usize
  let i1 ← lift (core.convert.num.FromU128U64.from i)
  let i2 ← Array.index_usize b 0#usize
  let i3 ← lift (core.convert.num.FromU128U64.from i2)
  let s0 ← lift (core.num.U128.wrapping_add i1 i3)
  let i4 ← Array.index_usize a 1#usize
  let i5 ← lift (core.convert.num.FromU128U64.from i4)
  let i6 ← Array.index_usize b 1#usize
  let i7 ← lift (core.convert.num.FromU128U64.from i6)
  let i8 ← lift (core.num.U128.wrapping_add i5 i7)
  let i9 ← s0 >>> 64#i32
  let s1 ← lift (core.num.U128.wrapping_add i8 i9)
  let i10 ← Array.index_usize a 2#usize
  let i11 ← lift (core.convert.num.FromU128U64.from i10)
  let i12 ← Array.index_usize b 2#usize
  let i13 ← lift (core.convert.num.FromU128U64.from i12)
  let i14 ← lift (core.num.U128.wrapping_add i11 i13)
  let i15 ← s1 >>> 64#i32
  let s2 ← lift (core.num.U128.wrapping_add i14 i15)
  let i16 ← Array.index_usize a 3#usize
  let i17 ← lift (core.convert.num.FromU128U64.from i16)
  let i18 ← Array.index_usize b 3#usize
  let i19 ← lift (core.convert.num.FromU128U64.from i18)
  let i20 ← lift (core.num.U128.wrapping_add i17 i19)
  let i21 ← s2 >>> 64#i32
  let s3 ← lift (core.num.U128.wrapping_add i20 i21)
  let mask ← lift (core.convert.num.FromU128U64.from core.num.U64.MAX)
  let i22 ← lift (s0 &&& mask)
  let r ← U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from i22
  let r1 ←
    core.result.Result.map_err
      field.add_limbs.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
      r ()
  let cf ←
    core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r1
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i23 ← lift (s1 &&& mask)
    let r2 ← U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from i23
    let r3 ←
      core.result.Result.map_err
        field.add_limbs.closure_1.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
        r2 ()
    let cf1 ←
      core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r3
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let i24 ← lift (s2 &&& mask)
      let r4 ← U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from i24
      let r5 ←
        core.result.Result.map_err
          field.add_limbs.closure_2.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
          r4 ()
      let cf2 ←
        core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
          r5
      match cf2 with
      | core.ops.control_flow.ControlFlow.Continue val2 =>
        let i25 ← lift (s3 &&& mask)
        let r6 ← U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from i25
        let r7 ←
          core.result.Result.map_err
            field.add_limbs.closure_3.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
            r6 ()
        let cf3 ←
          core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
            r7
        match cf3 with
        | core.ops.control_flow.ControlFlow.Continue val3 =>
          let i26 ← s3 >>> 64#i32
          ok (core.result.Result.Ok
            (Array.make 4#usize [ val, val1, val2, val3 ], i26 != 0#u128))
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
            ((Array Std.U64 4#usize) × Bool) (core.convert.FromSame
            error.Error) residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
          ((Array Std.U64 4#usize) × Bool) (core.convert.FromSame error.Error)
          residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        ((Array Std.U64 4#usize) × Bool) (core.convert.FromSame error.Error)
        residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      ((Array Std.U64 4#usize) × Bool) (core.convert.FromSame error.Error)
      residual

/-- [minroot_core::field::sub_limbs::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::sub_limbs::closure#3}::call_once]:
    Source: 'crates/minroot-core/src/field.rs', lines 314:46-314:67 -/
def
  field.sub_limbs.closure_3.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
  (c : field.sub_limbs.closure_3)
  (tupled_args : core.num.error.TryFromIntError) :
  Result error.Error
  := do
  ok error.Error.Truncation

/-- Trait implementation: [minroot_core::field::sub_limbs::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::sub_limbs::closure#3}]
    Source: 'crates/minroot-core/src/field.rs', lines 314:46-314:67 -/
@[reducible]
def
  field.sub_limbs.closure_3.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
  : core.ops.function.FnOnce field.sub_limbs.closure_3
  core.num.error.TryFromIntError error.Error := {
  call_once :=
    field.sub_limbs.closure_3.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
}

/-- [minroot_core::field::sub_limbs::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::sub_limbs::closure#2}::call_once]:
    Source: 'crates/minroot-core/src/field.rs', lines 313:46-313:67 -/
def
  field.sub_limbs.closure_2.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
  (c : field.sub_limbs.closure_2)
  (tupled_args : core.num.error.TryFromIntError) :
  Result error.Error
  := do
  ok error.Error.Truncation

/-- Trait implementation: [minroot_core::field::sub_limbs::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::sub_limbs::closure#2}]
    Source: 'crates/minroot-core/src/field.rs', lines 313:46-313:67 -/
@[reducible]
def
  field.sub_limbs.closure_2.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
  : core.ops.function.FnOnce field.sub_limbs.closure_2
  core.num.error.TryFromIntError error.Error := {
  call_once :=
    field.sub_limbs.closure_2.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
}

/-- [minroot_core::field::sub_limbs::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::sub_limbs::closure#1}::call_once]:
    Source: 'crates/minroot-core/src/field.rs', lines 312:46-312:67 -/
def
  field.sub_limbs.closure_1.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
  (c : field.sub_limbs.closure_1)
  (tupled_args : core.num.error.TryFromIntError) :
  Result error.Error
  := do
  ok error.Error.Truncation

/-- Trait implementation: [minroot_core::field::sub_limbs::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::sub_limbs::closure#1}]
    Source: 'crates/minroot-core/src/field.rs', lines 312:46-312:67 -/
@[reducible]
def
  field.sub_limbs.closure_1.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
  : core.ops.function.FnOnce field.sub_limbs.closure_1
  core.num.error.TryFromIntError error.Error := {
  call_once :=
    field.sub_limbs.closure_1.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
}

/-- [minroot_core::field::sub_limbs::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::sub_limbs::closure}::call_once]:
    Source: 'crates/minroot-core/src/field.rs', lines 311:46-311:67 -/
def
  field.sub_limbs.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
  (c : field.sub_limbs.closure) (tupled_args : core.num.error.TryFromIntError)
  :
  Result error.Error
  := do
  ok error.Error.Truncation

/-- Trait implementation: [minroot_core::field::sub_limbs::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::sub_limbs::closure}]
    Source: 'crates/minroot-core/src/field.rs', lines 311:46-311:67 -/
@[reducible]
def
  field.sub_limbs.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
  : core.ops.function.FnOnce field.sub_limbs.closure
  core.num.error.TryFromIntError error.Error := {
  call_once :=
    field.sub_limbs.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
}

/-- [minroot_core::field::sub_limbs]:
    Source: 'crates/minroot-core/src/field.rs', lines 302:0-316:1 -/
def field.sub_limbs
  (a : Array Std.U64 4#usize) (b : Array Std.U64 4#usize) :
  Result (core.result.Result ((Array Std.U64 4#usize) × Bool) error.Error)
  := do
  let i ← Array.index_usize a 0#usize
  let i1 ← lift (core.convert.num.FromU128U64.from i)
  let i2 ← Array.index_usize b 0#usize
  let i3 ← lift (core.convert.num.FromU128U64.from i2)
  let d0 ← lift (core.num.U128.wrapping_sub i1 i3)
  let i4 ← d0 >>> 127#i32
  let bo0 ← lift (core.convert.num.FromU128Bool.from (i4 != 0#u128))
  let i5 ← Array.index_usize a 1#usize
  let i6 ← lift (core.convert.num.FromU128U64.from i5)
  let i7 ← Array.index_usize b 1#usize
  let i8 ← lift (core.convert.num.FromU128U64.from i7)
  let i9 ← lift (core.num.U128.wrapping_sub i6 i8)
  let d1 ← lift (core.num.U128.wrapping_sub i9 bo0)
  let i10 ← d1 >>> 127#i32
  let bo1 ← lift (core.convert.num.FromU128Bool.from (i10 != 0#u128))
  let i11 ← Array.index_usize a 2#usize
  let i12 ← lift (core.convert.num.FromU128U64.from i11)
  let i13 ← Array.index_usize b 2#usize
  let i14 ← lift (core.convert.num.FromU128U64.from i13)
  let i15 ← lift (core.num.U128.wrapping_sub i12 i14)
  let d2 ← lift (core.num.U128.wrapping_sub i15 bo1)
  let i16 ← d2 >>> 127#i32
  let bo2 ← lift (core.convert.num.FromU128Bool.from (i16 != 0#u128))
  let i17 ← Array.index_usize a 3#usize
  let i18 ← lift (core.convert.num.FromU128U64.from i17)
  let i19 ← Array.index_usize b 3#usize
  let i20 ← lift (core.convert.num.FromU128U64.from i19)
  let i21 ← lift (core.num.U128.wrapping_sub i18 i20)
  let d3 ← lift (core.num.U128.wrapping_sub i21 bo2)
  let mask ← lift (core.convert.num.FromU128U64.from core.num.U64.MAX)
  let i22 ← lift (d0 &&& mask)
  let r ← U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from i22
  let r1 ←
    core.result.Result.map_err
      field.sub_limbs.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
      r ()
  let cf ←
    core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r1
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i23 ← lift (d1 &&& mask)
    let r2 ← U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from i23
    let r3 ←
      core.result.Result.map_err
        field.sub_limbs.closure_1.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
        r2 ()
    let cf1 ←
      core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r3
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let i24 ← lift (d2 &&& mask)
      let r4 ← U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from i24
      let r5 ←
        core.result.Result.map_err
          field.sub_limbs.closure_2.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
          r4 ()
      let cf2 ←
        core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
          r5
      match cf2 with
      | core.ops.control_flow.ControlFlow.Continue val2 =>
        let i25 ← lift (d3 &&& mask)
        let r6 ← U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from i25
        let r7 ←
          core.result.Result.map_err
            field.sub_limbs.closure_3.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
            r6 ()
        let cf3 ←
          core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
            r7
        match cf3 with
        | core.ops.control_flow.ControlFlow.Continue val3 =>
          let i26 ← d3 >>> 127#i32
          ok (core.result.Result.Ok
            (Array.make 4#usize [ val, val1, val2, val3 ], i26 != 0#u128))
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
            ((Array Std.U64 4#usize) × Bool) (core.convert.FromSame
            error.Error) residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
          ((Array Std.U64 4#usize) × Bool) (core.convert.FromSame error.Error)
          residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        ((Array Std.U64 4#usize) × Bool) (core.convert.FromSame error.Error)
        residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      ((Array Std.U64 4#usize) × Bool) (core.convert.FromSame error.Error)
      residual

/-- [minroot_core::field::gte_modulus]:
    Source: 'crates/minroot-core/src/field.rs', lines 321:0-331:1 -/
def field.gte_modulus
  (a : Array Std.U64 4#usize) (modulus : Array Std.U64 4#usize) :
  Result Bool
  := do
  let i ← Array.index_usize a 3#usize
  let i1 ← Array.index_usize modulus 3#usize
  if i != i1
  then ok (i > i1)
  else
    let i2 ← Array.index_usize a 2#usize
    let i3 ← Array.index_usize modulus 2#usize
    if i2 != i3
    then ok (i2 > i3)
    else
      let i4 ← Array.index_usize a 1#usize
      let i5 ← Array.index_usize modulus 1#usize
      if i4 != i5
      then ok (i4 > i5)
      else
        let i6 ← Array.index_usize a 0#usize
        let i7 ← Array.index_usize modulus 0#usize
        ok (i6 >= i7)

/-- [minroot_core::field::mod_add]:
    Source: 'crates/minroot-core/src/field.rs', lines 344:0-356:1 -/
def field.mod_add
  (a : Array Std.U64 4#usize) (b : Array Std.U64 4#usize)
  (modulus : Array Std.U64 4#usize) :
  Result (core.result.Result (Array Std.U64 4#usize) error.Error)
  := do
  let r ← field.add_limbs a b
  let cf ←
    core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let (sum, carry) := val
    if carry
    then
      let r1 ← field.sub_limbs sum modulus
      let cf1 ←
        core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
          r1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue val1 =>
        let (result, _) := val1
        ok (core.result.Result.Ok result)
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
          (Array Std.U64 4#usize) (core.convert.FromSame error.Error) residual
    else
      let b1 ← field.gte_modulus sum modulus
      if b1
      then
        let r1 ← field.sub_limbs sum modulus
        let cf1 ←
          core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
            r1
        match cf1 with
        | core.ops.control_flow.ControlFlow.Continue val1 =>
          let (result, _) := val1
          ok (core.result.Result.Ok result)
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
            (Array Std.U64 4#usize) (core.convert.FromSame error.Error)
            residual
      else ok (core.result.Result.Ok sum)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      (Array Std.U64 4#usize) (core.convert.FromSame error.Error) residual

/-- [minroot_core::field::mod_sub]:
    Source: 'crates/minroot-core/src/field.rs', lines 366:0-378:1 -/
def field.mod_sub
  (a : Array Std.U64 4#usize) (b : Array Std.U64 4#usize)
  (modulus : Array Std.U64 4#usize) :
  Result (core.result.Result (Array Std.U64 4#usize) error.Error)
  := do
  let r ← field.sub_limbs a b
  let cf ←
    core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let (diff, borrow) := val
    if borrow
    then
      let r1 ← field.add_limbs diff modulus
      let cf1 ←
        core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
          r1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue val1 =>
        let (result, _) := val1
        ok (core.result.Result.Ok result)
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
          (Array Std.U64 4#usize) (core.convert.FromSame error.Error) residual
    else ok (core.result.Result.Ok diff)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      (Array Std.U64 4#usize) (core.convert.FromSame error.Error) residual

/-- [minroot_core::field::shift_left_one]:
    Source: 'crates/minroot-core/src/field.rs', lines 568:0-575:1 -/
def field.shift_left_one
  (a : Array Std.U64 4#usize) : Result (Array Std.U64 4#usize) := do
  let i ← Array.index_usize a 0#usize
  let i1 ← i <<< 1#i32
  let i2 ← Array.index_usize a 1#usize
  let i3 ← i2 <<< 1#i32
  let i4 ← i >>> 63#i32
  let i5 ← lift (i3 ||| i4)
  let i6 ← Array.index_usize a 2#usize
  let i7 ← i6 <<< 1#i32
  let i8 ← i2 >>> 63#i32
  let i9 ← lift (i7 ||| i8)
  let i10 ← Array.index_usize a 3#usize
  let i11 ← i10 <<< 1#i32
  let i12 ← i6 >>> 63#i32
  let i13 ← lift (i11 ||| i12)
  ok (Array.make 4#usize [ i1, i5, i9, i13 ])

/-- [minroot_core::field::reduce_wide_rec]:
    Source: 'crates/minroot-core/src/field.rs', lines 540:0-562:1 -/
def field.reduce_wide_rec
  (wide : Array Std.U64 8#usize) (modulus : Array Std.U64 4#usize)
  (remaining : Std.Usize) (acc : Array Std.U64 4#usize) :
  Result (core.result.Result (Array Std.U64 4#usize) error.Error)
  := do
  if remaining = 0#usize
  then ok (core.result.Result.Ok acc)
  else
    let bit ← remaining - 1#usize
    let shifted ← field.shift_left_one acc
    let limb_idx ← bit / 64#usize
    let bit_idx ← bit % 64#usize
    let i ← Array.index_usize wide limb_idx
    let i1 ← i >>> bit_idx
    let incoming ← lift (i1 &&& 1#u64)
    let i2 ← Array.index_usize shifted 0#usize
    let i3 ← lift (i2 ||| incoming)
    let i4 ← Array.index_usize shifted 1#usize
    let i5 ← Array.index_usize shifted 2#usize
    let i6 ← Array.index_usize shifted 3#usize
    let b ← field.gte_modulus (Array.make 4#usize [ i3, i4, i5, i6 ]) modulus
    if b
    then
      let r ← field.sub_limbs (Array.make 4#usize [ i3, i4, i5, i6 ]) modulus
      let cf ←
        core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
      match cf with
      | core.ops.control_flow.ControlFlow.Continue val =>
        let (next, _) := val
        field.reduce_wide_rec wide modulus bit next
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
          (Array Std.U64 4#usize) (core.convert.FromSame error.Error) residual
    else
      field.reduce_wide_rec wide modulus bit
        (Array.make 4#usize [ i3, i4, i5, i6 ])
partial_fixpoint

/-- [minroot_core::field::reduce_wide]:
    Source: 'crates/minroot-core/src/field.rs', lines 525:0-530:1 -/
def field.reduce_wide
  (wide : Array Std.U64 8#usize) (modulus : Array Std.U64 4#usize) :
  Result (core.result.Result (Array Std.U64 4#usize) error.Error)
  := do
  let i ← field.LIMBS * 2#usize
  let i1 ← i * 64#usize
  let a := Array.repeat 4#usize 0#u64
  field.reduce_wide_rec wide modulus i1 a

/-- [minroot_core::field::mul_wide::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::mul_wide::closure#7}::call_once]:
    Source: 'crates/minroot-core/src/field.rs', lines 516:34-516:55 -/
def
  field.mul_wide.closure_7.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
  (c : field.mul_wide.closure_7) (tupled_args : core.num.error.TryFromIntError)
  :
  Result error.Error
  := do
  ok error.Error.Truncation

/-- Trait implementation: [minroot_core::field::mul_wide::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::mul_wide::closure#7}]
    Source: 'crates/minroot-core/src/field.rs', lines 516:34-516:55 -/
@[reducible]
def
  field.mul_wide.closure_7.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
  : core.ops.function.FnOnce field.mul_wide.closure_7
  core.num.error.TryFromIntError error.Error := {
  call_once :=
    field.mul_wide.closure_7.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
}

/-- [minroot_core::field::mul_wide::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::mul_wide::closure#6}::call_once]:
    Source: 'crates/minroot-core/src/field.rs', lines 515:34-515:55 -/
def
  field.mul_wide.closure_6.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
  (c : field.mul_wide.closure_6) (tupled_args : core.num.error.TryFromIntError)
  :
  Result error.Error
  := do
  ok error.Error.Truncation

/-- Trait implementation: [minroot_core::field::mul_wide::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::mul_wide::closure#6}]
    Source: 'crates/minroot-core/src/field.rs', lines 515:34-515:55 -/
@[reducible]
def
  field.mul_wide.closure_6.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
  : core.ops.function.FnOnce field.mul_wide.closure_6
  core.num.error.TryFromIntError error.Error := {
  call_once :=
    field.mul_wide.closure_6.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
}

/-- [minroot_core::field::mul_wide::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::mul_wide::closure#5}::call_once]:
    Source: 'crates/minroot-core/src/field.rs', lines 514:34-514:55 -/
def
  field.mul_wide.closure_5.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
  (c : field.mul_wide.closure_5) (tupled_args : core.num.error.TryFromIntError)
  :
  Result error.Error
  := do
  ok error.Error.Truncation

/-- Trait implementation: [minroot_core::field::mul_wide::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::mul_wide::closure#5}]
    Source: 'crates/minroot-core/src/field.rs', lines 514:34-514:55 -/
@[reducible]
def
  field.mul_wide.closure_5.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
  : core.ops.function.FnOnce field.mul_wide.closure_5
  core.num.error.TryFromIntError error.Error := {
  call_once :=
    field.mul_wide.closure_5.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
}

/-- [minroot_core::field::mul_wide::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::mul_wide::closure#4}::call_once]:
    Source: 'crates/minroot-core/src/field.rs', lines 513:34-513:55 -/
def
  field.mul_wide.closure_4.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
  (c : field.mul_wide.closure_4) (tupled_args : core.num.error.TryFromIntError)
  :
  Result error.Error
  := do
  ok error.Error.Truncation

/-- Trait implementation: [minroot_core::field::mul_wide::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::mul_wide::closure#4}]
    Source: 'crates/minroot-core/src/field.rs', lines 513:34-513:55 -/
@[reducible]
def
  field.mul_wide.closure_4.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
  : core.ops.function.FnOnce field.mul_wide.closure_4
  core.num.error.TryFromIntError error.Error := {
  call_once :=
    field.mul_wide.closure_4.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
}

/-- [minroot_core::field::mul_wide::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::mul_wide::closure#3}::call_once]:
    Source: 'crates/minroot-core/src/field.rs', lines 512:34-512:55 -/
def
  field.mul_wide.closure_3.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
  (c : field.mul_wide.closure_3) (tupled_args : core.num.error.TryFromIntError)
  :
  Result error.Error
  := do
  ok error.Error.Truncation

/-- Trait implementation: [minroot_core::field::mul_wide::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::mul_wide::closure#3}]
    Source: 'crates/minroot-core/src/field.rs', lines 512:34-512:55 -/
@[reducible]
def
  field.mul_wide.closure_3.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
  : core.ops.function.FnOnce field.mul_wide.closure_3
  core.num.error.TryFromIntError error.Error := {
  call_once :=
    field.mul_wide.closure_3.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
}

/-- [minroot_core::field::mul_wide::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::mul_wide::closure#2}::call_once]:
    Source: 'crates/minroot-core/src/field.rs', lines 511:34-511:55 -/
def
  field.mul_wide.closure_2.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
  (c : field.mul_wide.closure_2) (tupled_args : core.num.error.TryFromIntError)
  :
  Result error.Error
  := do
  ok error.Error.Truncation

/-- Trait implementation: [minroot_core::field::mul_wide::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::mul_wide::closure#2}]
    Source: 'crates/minroot-core/src/field.rs', lines 511:34-511:55 -/
@[reducible]
def
  field.mul_wide.closure_2.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
  : core.ops.function.FnOnce field.mul_wide.closure_2
  core.num.error.TryFromIntError error.Error := {
  call_once :=
    field.mul_wide.closure_2.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
}

/-- [minroot_core::field::mul_wide::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::mul_wide::closure#1}::call_once]:
    Source: 'crates/minroot-core/src/field.rs', lines 510:34-510:55 -/
def
  field.mul_wide.closure_1.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
  (c : field.mul_wide.closure_1) (tupled_args : core.num.error.TryFromIntError)
  :
  Result error.Error
  := do
  ok error.Error.Truncation

/-- Trait implementation: [minroot_core::field::mul_wide::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::mul_wide::closure#1}]
    Source: 'crates/minroot-core/src/field.rs', lines 510:34-510:55 -/
@[reducible]
def
  field.mul_wide.closure_1.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
  : core.ops.function.FnOnce field.mul_wide.closure_1
  core.num.error.TryFromIntError error.Error := {
  call_once :=
    field.mul_wide.closure_1.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
}

/-- [minroot_core::field::mul_wide::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::mul_wide::closure}::call_once]:
    Source: 'crates/minroot-core/src/field.rs', lines 509:34-509:55 -/
def
  field.mul_wide.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
  (c : field.mul_wide.closure) (tupled_args : core.num.error.TryFromIntError) :
  Result error.Error
  := do
  ok error.Error.Truncation

/-- Trait implementation: [minroot_core::field::mul_wide::{core::ops::function::FnOnce<(core::num::error::TryFromIntError), minroot_core::error::Error> for minroot_core::field::mul_wide::closure}]
    Source: 'crates/minroot-core/src/field.rs', lines 509:34-509:55 -/
@[reducible]
def field.mul_wide.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
  : core.ops.function.FnOnce field.mul_wide.closure
  core.num.error.TryFromIntError error.Error := {
  call_once :=
    field.mul_wide.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError.call_once
}

/-- [minroot_core::field::mul_wide]:
    Source: 'crates/minroot-core/src/field.rs', lines 466:0-518:1 -/
def field.mul_wide
  (a : Array Std.U64 4#usize) (b : Array Std.U64 4#usize) :
  Result (core.result.Result (Array Std.U64 8#usize) error.Error)
  := do
  let mask ← lift (core.convert.num.FromU128U64.from core.num.U64.MAX)
  let i ← Array.index_usize a 0#usize
  let i1 ← lift (core.convert.num.FromU128U64.from i)
  let i2 ← Array.index_usize b 0#usize
  let i3 ← lift (core.convert.num.FromU128U64.from i2)
  let t ← lift (core.num.U128.wrapping_mul i1 i3)
  let r0 ← lift (t &&& mask)
  let i4 ← lift (core.convert.num.FromU128U64.from i)
  let i5 ← Array.index_usize b 1#usize
  let i6 ← lift (core.convert.num.FromU128U64.from i5)
  let i7 ← lift (core.num.U128.wrapping_mul i4 i6)
  let i8 ← t >>> 64#i32
  let t1 ← lift (core.num.U128.wrapping_add i7 i8)
  let r1 ← lift (t1 &&& mask)
  let i9 ← lift (core.convert.num.FromU128U64.from i)
  let i10 ← Array.index_usize b 2#usize
  let i11 ← lift (core.convert.num.FromU128U64.from i10)
  let i12 ← lift (core.num.U128.wrapping_mul i9 i11)
  let i13 ← t1 >>> 64#i32
  let t2 ← lift (core.num.U128.wrapping_add i12 i13)
  let r2 ← lift (t2 &&& mask)
  let i14 ← lift (core.convert.num.FromU128U64.from i)
  let i15 ← Array.index_usize b 3#usize
  let i16 ← lift (core.convert.num.FromU128U64.from i15)
  let i17 ← lift (core.num.U128.wrapping_mul i14 i16)
  let i18 ← t2 >>> 64#i32
  let t3 ← lift (core.num.U128.wrapping_add i17 i18)
  let r3 ← lift (t3 &&& mask)
  let r4 ← t3 >>> 64#i32
  let i19 ← Array.index_usize a 1#usize
  let i20 ← lift (core.convert.num.FromU128U64.from i19)
  let i21 ← lift (core.convert.num.FromU128U64.from i2)
  let i22 ← lift (core.num.U128.wrapping_mul i20 i21)
  let t4 ← lift (core.num.U128.wrapping_add i22 r1)
  let r11 ← lift (t4 &&& mask)
  let i23 ← lift (core.convert.num.FromU128U64.from i19)
  let i24 ← lift (core.convert.num.FromU128U64.from i5)
  let i25 ← lift (core.num.U128.wrapping_mul i23 i24)
  let i26 ← lift (core.num.U128.wrapping_add i25 r2)
  let i27 ← t4 >>> 64#i32
  let t5 ← lift (core.num.U128.wrapping_add i26 i27)
  let r21 ← lift (t5 &&& mask)
  let i28 ← lift (core.convert.num.FromU128U64.from i19)
  let i29 ← lift (core.convert.num.FromU128U64.from i10)
  let i30 ← lift (core.num.U128.wrapping_mul i28 i29)
  let i31 ← lift (core.num.U128.wrapping_add i30 r3)
  let i32 ← t5 >>> 64#i32
  let t6 ← lift (core.num.U128.wrapping_add i31 i32)
  let r31 ← lift (t6 &&& mask)
  let i33 ← lift (core.convert.num.FromU128U64.from i19)
  let i34 ← lift (core.convert.num.FromU128U64.from i15)
  let i35 ← lift (core.num.U128.wrapping_mul i33 i34)
  let i36 ← lift (core.num.U128.wrapping_add i35 r4)
  let i37 ← t6 >>> 64#i32
  let t7 ← lift (core.num.U128.wrapping_add i36 i37)
  let r41 ← lift (t7 &&& mask)
  let r5 ← t7 >>> 64#i32
  let i38 ← Array.index_usize a 2#usize
  let i39 ← lift (core.convert.num.FromU128U64.from i38)
  let i40 ← lift (core.convert.num.FromU128U64.from i2)
  let i41 ← lift (core.num.U128.wrapping_mul i39 i40)
  let t8 ← lift (core.num.U128.wrapping_add i41 r21)
  let r22 ← lift (t8 &&& mask)
  let i42 ← lift (core.convert.num.FromU128U64.from i38)
  let i43 ← lift (core.convert.num.FromU128U64.from i5)
  let i44 ← lift (core.num.U128.wrapping_mul i42 i43)
  let i45 ← lift (core.num.U128.wrapping_add i44 r31)
  let i46 ← t8 >>> 64#i32
  let t9 ← lift (core.num.U128.wrapping_add i45 i46)
  let r32 ← lift (t9 &&& mask)
  let i47 ← lift (core.convert.num.FromU128U64.from i38)
  let i48 ← lift (core.convert.num.FromU128U64.from i10)
  let i49 ← lift (core.num.U128.wrapping_mul i47 i48)
  let i50 ← lift (core.num.U128.wrapping_add i49 r41)
  let i51 ← t9 >>> 64#i32
  let t10 ← lift (core.num.U128.wrapping_add i50 i51)
  let r42 ← lift (t10 &&& mask)
  let i52 ← lift (core.convert.num.FromU128U64.from i38)
  let i53 ← lift (core.convert.num.FromU128U64.from i15)
  let i54 ← lift (core.num.U128.wrapping_mul i52 i53)
  let i55 ← lift (core.num.U128.wrapping_add i54 r5)
  let i56 ← t10 >>> 64#i32
  let t11 ← lift (core.num.U128.wrapping_add i55 i56)
  let r51 ← lift (t11 &&& mask)
  let r6 ← t11 >>> 64#i32
  let i57 ← Array.index_usize a 3#usize
  let i58 ← lift (core.convert.num.FromU128U64.from i57)
  let i59 ← lift (core.convert.num.FromU128U64.from i2)
  let i60 ← lift (core.num.U128.wrapping_mul i58 i59)
  let t12 ← lift (core.num.U128.wrapping_add i60 r32)
  let r33 ← lift (t12 &&& mask)
  let i61 ← lift (core.convert.num.FromU128U64.from i57)
  let i62 ← lift (core.convert.num.FromU128U64.from i5)
  let i63 ← lift (core.num.U128.wrapping_mul i61 i62)
  let i64 ← lift (core.num.U128.wrapping_add i63 r42)
  let i65 ← t12 >>> 64#i32
  let t13 ← lift (core.num.U128.wrapping_add i64 i65)
  let r43 ← lift (t13 &&& mask)
  let i66 ← lift (core.convert.num.FromU128U64.from i57)
  let i67 ← lift (core.convert.num.FromU128U64.from i10)
  let i68 ← lift (core.num.U128.wrapping_mul i66 i67)
  let i69 ← lift (core.num.U128.wrapping_add i68 r51)
  let i70 ← t13 >>> 64#i32
  let t14 ← lift (core.num.U128.wrapping_add i69 i70)
  let r52 ← lift (t14 &&& mask)
  let i71 ← lift (core.convert.num.FromU128U64.from i57)
  let i72 ← lift (core.convert.num.FromU128U64.from i15)
  let i73 ← lift (core.num.U128.wrapping_mul i71 i72)
  let i74 ← lift (core.num.U128.wrapping_add i73 r6)
  let i75 ← t14 >>> 64#i32
  let t15 ← lift (core.num.U128.wrapping_add i74 i75)
  let r61 ← lift (t15 &&& mask)
  let r7 ← t15 >>> 64#i32
  let r ← U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from r0
  let r8 ←
    core.result.Result.map_err
      field.mul_wide.closure.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
      r ()
  let cf ←
    core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r8
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r9 ← U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from r11
    let r10 ←
      core.result.Result.map_err
        field.mul_wide.closure_1.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
        r9 ()
    let cf1 ←
      core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r10
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let r12 ← U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from r22
      let r13 ←
        core.result.Result.map_err
          field.mul_wide.closure_2.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
          r12 ()
      let cf2 ←
        core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
          r13
      match cf2 with
      | core.ops.control_flow.ControlFlow.Continue val2 =>
        let r14 ←
          U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from r33
        let r15 ←
          core.result.Result.map_err
            field.mul_wide.closure_3.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
            r14 ()
        let cf3 ←
          core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
            r15
        match cf3 with
        | core.ops.control_flow.ControlFlow.Continue val3 =>
          let r16 ←
            U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from r43
          let r17 ←
            core.result.Result.map_err
              field.mul_wide.closure_4.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
              r16 ()
          let cf4 ←
            core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
              r17
          match cf4 with
          | core.ops.control_flow.ControlFlow.Continue val4 =>
            let r18 ←
              U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from r52
            let r19 ←
              core.result.Result.map_err
                field.mul_wide.closure_5.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
                r18 ()
            let cf5 ←
              core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
                r19
            match cf5 with
            | core.ops.control_flow.ControlFlow.Continue val5 =>
              let r20 ←
                U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from r61
              let r23 ←
                core.result.Result.map_err
                  field.mul_wide.closure_6.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
                  r20 ()
              let cf6 ←
                core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
                  r23
              match cf6 with
              | core.ops.control_flow.ControlFlow.Continue val6 =>
                let r24 ←
                  U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from r7
                let r25 ←
                  core.result.Result.map_err
                    field.mul_wide.closure_7.Insts.CoreOpsFunctionFnOnceTupleTryFromIntErrorError
                    r24 ()
                let cf7 ←
                  core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
                    r25
                match cf7 with
                | core.ops.control_flow.ControlFlow.Continue val7 =>
                  ok (core.result.Result.Ok
                    (Array.make 8#usize [
                      val, val1, val2, val3, val4, val5, val6, val7
                      ]))
                | core.ops.control_flow.ControlFlow.Break residual =>
                  core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
                    (Array Std.U64 8#usize) (core.convert.FromSame error.Error)
                    residual
              | core.ops.control_flow.ControlFlow.Break residual =>
                core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
                  (Array Std.U64 8#usize) (core.convert.FromSame error.Error)
                  residual
            | core.ops.control_flow.ControlFlow.Break residual =>
              core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
                (Array Std.U64 8#usize) (core.convert.FromSame error.Error)
                residual
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
              (Array Std.U64 8#usize) (core.convert.FromSame error.Error)
              residual
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
            (Array Std.U64 8#usize) (core.convert.FromSame error.Error)
            residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
          (Array Std.U64 8#usize) (core.convert.FromSame error.Error) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        (Array Std.U64 8#usize) (core.convert.FromSame error.Error) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      (Array Std.U64 8#usize) (core.convert.FromSame error.Error) residual

/-- [minroot_core::field::mod_mul]:
    Source: 'crates/minroot-core/src/field.rs', lines 390:0-397:1 -/
def field.mod_mul
  (a : Array Std.U64 4#usize) (b : Array Std.U64 4#usize)
  (modulus : Array Std.U64 4#usize) :
  Result (core.result.Result (Array Std.U64 4#usize) error.Error)
  := do
  let r ← field.mul_wide a b
  let cf ←
    core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    field.reduce_wide val modulus
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      (Array Std.U64 4#usize) (core.convert.FromSame error.Error) residual

/-- [minroot_core::field::mod_pow_rec]:
    Source: 'crates/minroot-core/src/field.rs', lines 429:0-450:1 -/
def field.mod_pow_rec
  (base : Array Std.U64 4#usize) (exp : Array Std.U64 4#usize)
  (modulus : Array Std.U64 4#usize) (remaining : Std.Usize)
  (acc : Array Std.U64 4#usize) :
  Result (core.result.Result (Array Std.U64 4#usize) error.Error)
  := do
  if remaining = 0#usize
  then ok (core.result.Result.Ok acc)
  else
    let bit ← remaining - 1#usize
    let r ← field.mod_mul acc acc modulus
    let cf ←
      core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let limb_idx ← bit / 64#usize
      let bit_idx ← bit % 64#usize
      let i ← Array.index_usize exp limb_idx
      let i1 ← i >>> bit_idx
      let i2 ← lift (i1 &&& 1#u64)
      if i2 = 1#u64
      then
        let r1 ← field.mod_mul val base modulus
        let cf1 ←
          core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
            r1
        match cf1 with
        | core.ops.control_flow.ControlFlow.Continue val1 =>
          field.mod_pow_rec base exp modulus bit val1
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
            (Array Std.U64 4#usize) (core.convert.FromSame error.Error)
            residual
      else field.mod_pow_rec base exp modulus bit val
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        (Array Std.U64 4#usize) (core.convert.FromSame error.Error) residual
partial_fixpoint

/-- [minroot_core::field::mod_pow]:
    Source: 'crates/minroot-core/src/field.rs', lines 411:0-418:1 -/
def field.mod_pow
  (base : Array Std.U64 4#usize) (exp : Array Std.U64 4#usize)
  (num_bits : Std.Usize) (modulus : Array Std.U64 4#usize) :
  Result (core.result.Result (Array Std.U64 4#usize) error.Error)
  := do
  field.mod_pow_rec base exp modulus num_bits
    (Array.make 4#usize [ 1#u64, 0#u64, 0#u64, 0#u64 ])

end minroot_core
