-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [minroot_core]: type definitions
import Aeneas
import MinrootCore.Code.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace minroot_core

/-- [minroot_core::error::Error]
    Source: 'crates/minroot-core/src/error.rs', lines 7:0-29:1
    Visibility: public -/
@[discriminant isize]
inductive error.Error where
| OutOfRange : Str → error.Error
| CoefficientCountMismatch : Std.Usize → Std.Usize → error.Error
| DivisionByZero : error.Error
| ZeroIterations : error.Error
| Truncation : error.Error

/-- [minroot_core::field::add_limbs::closure#3]
    Source: 'crates/minroot-core/src/field.rs', lines 286:46-286:67 -/
@[reducible]
def field.add_limbs.closure_3 := Unit

/-- [minroot_core::field::add_limbs::closure#2]
    Source: 'crates/minroot-core/src/field.rs', lines 285:46-285:67 -/
@[reducible]
def field.add_limbs.closure_2 := Unit

/-- [minroot_core::field::add_limbs::closure#1]
    Source: 'crates/minroot-core/src/field.rs', lines 284:46-284:67 -/
@[reducible]
def field.add_limbs.closure_1 := Unit

/-- [minroot_core::field::add_limbs::closure]
    Source: 'crates/minroot-core/src/field.rs', lines 283:46-283:67 -/
@[reducible]
def field.add_limbs.closure := Unit

/-- [minroot_core::field::sub_limbs::closure#3]
    Source: 'crates/minroot-core/src/field.rs', lines 314:46-314:67 -/
@[reducible]
def field.sub_limbs.closure_3 := Unit

/-- [minroot_core::field::sub_limbs::closure#2]
    Source: 'crates/minroot-core/src/field.rs', lines 313:46-313:67 -/
@[reducible]
def field.sub_limbs.closure_2 := Unit

/-- [minroot_core::field::sub_limbs::closure#1]
    Source: 'crates/minroot-core/src/field.rs', lines 312:46-312:67 -/
@[reducible]
def field.sub_limbs.closure_1 := Unit

/-- [minroot_core::field::sub_limbs::closure]
    Source: 'crates/minroot-core/src/field.rs', lines 311:46-311:67 -/
@[reducible]
def field.sub_limbs.closure := Unit

/-- [minroot_core::field::mul_wide::closure#7]
    Source: 'crates/minroot-core/src/field.rs', lines 516:34-516:55 -/
@[reducible]
def field.mul_wide.closure_7 := Unit

/-- [minroot_core::field::mul_wide::closure#6]
    Source: 'crates/minroot-core/src/field.rs', lines 515:34-515:55 -/
@[reducible]
def field.mul_wide.closure_6 := Unit

/-- [minroot_core::field::mul_wide::closure#5]
    Source: 'crates/minroot-core/src/field.rs', lines 514:34-514:55 -/
@[reducible]
def field.mul_wide.closure_5 := Unit

/-- [minroot_core::field::mul_wide::closure#4]
    Source: 'crates/minroot-core/src/field.rs', lines 513:34-513:55 -/
@[reducible]
def field.mul_wide.closure_4 := Unit

/-- [minroot_core::field::mul_wide::closure#3]
    Source: 'crates/minroot-core/src/field.rs', lines 512:34-512:55 -/
@[reducible]
def field.mul_wide.closure_3 := Unit

/-- [minroot_core::field::mul_wide::closure#2]
    Source: 'crates/minroot-core/src/field.rs', lines 511:34-511:55 -/
@[reducible]
def field.mul_wide.closure_2 := Unit

/-- [minroot_core::field::mul_wide::closure#1]
    Source: 'crates/minroot-core/src/field.rs', lines 510:34-510:55 -/
@[reducible]
def field.mul_wide.closure_1 := Unit

/-- [minroot_core::field::mul_wide::closure]
    Source: 'crates/minroot-core/src/field.rs', lines 509:34-509:55 -/
@[reducible]
def field.mul_wide.closure := Unit

end minroot_core
