-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [minroot_core]: type definitions
import Aeneas
import MinrootCore.Code.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace minroot_core

/-- [minroot_core::error::Error]
    Source: 'crates/minroot-core/src/error.rs', lines 7:0-29:1
    Visibility: public -/
@[discriminant isize]
inductive error.Error where
| OutOfRange : Str → error.Error
| CoefficientCountMismatch : Std.Usize → Std.Usize → error.Error
| DivisionByZero : error.Error
| ZeroIterations : error.Error
| Truncation : error.Error

/-- [minroot_core::field::sub_limbs::closure#3]
    Source: 'crates/minroot-core/src/field.rs', lines 324:46-324:67 -/
@[reducible]
def field.sub_limbs.closure_3 := Unit

/-- [minroot_core::field::sub_limbs::closure#2]
    Source: 'crates/minroot-core/src/field.rs', lines 323:46-323:67 -/
@[reducible]
def field.sub_limbs.closure_2 := Unit

/-- [minroot_core::field::sub_limbs::closure#1]
    Source: 'crates/minroot-core/src/field.rs', lines 322:46-322:67 -/
@[reducible]
def field.sub_limbs.closure_1 := Unit

/-- [minroot_core::field::sub_limbs::closure]
    Source: 'crates/minroot-core/src/field.rs', lines 321:46-321:67 -/
@[reducible]
def field.sub_limbs.closure := Unit

end minroot_core
