-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [minroot_core]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/-- [core::num::error::TryFromIntError]
    Source: '/rustc/library/core/src/num/error.rs', lines 10:0-10:26
    Name pattern: [core::num::error::TryFromIntError]
    Visibility: public

    Modeled as a concrete single-constructor type (the real Rust type is an
    opaque zero-field struct).  A concrete, inhabited definition is required so
    that the narrowing `u128 -> u64` `try_from` can produce an `Err` value on
    overflow; the previous `axiom : Type` left the error branch uninhabited. -/
@[rust_type "core::num::error::TryFromIntError"]
inductive core.num.error.TryFromIntError where
  | mk

